using System.Collections.Generic;
using UnityEngine;


// I don't think any human being can fathom how much fun I had writing this script. top 10 best scripts of my life.
namespace Npc
{
    public static class GenericLines
    {
        public static string GetRandomLine(string category)
        {
            if (!LinesByCategory.TryGetValue(category, out var lines)) return string.Empty;

            return lines[Random.Range(0, lines.Count)];
        }
        private static readonly Dictionary<string, List<string>> LinesByCategory = new Dictionary<string, List<string>>()
        {
            //Player//
            { "Call", new List<string> {
                "Come here for a sec.", 
                "Hey, come here for a bit.", 
                "Could you come here for a moment?", 
                "Pop over here for a sec.",
                "Mind coming over here?",  
                "Could you come here a sec?",  
                "Would you come here for a bit?",  
                "Can you come over for a moment?",  
                "Come here when you can.",  
                "Over here for a sec?",  
                "Would you step over here?",  
                "Can I get you over here for a moment?",  
                "Could you come this way a bit?",  
                "Over here, if you don’t mind.",  
                "Can you come closer for a sec?",  
                "Would you come by for a bit?",  
                "Can you step over here a moment?",  
                "Mind stepping over here?",  
                "Would you come stand by me for a sec?",  
                "Over here, just for a moment.",  
                "Could I call you over here a sec?",  
                "Come here for a moment, please.",  
                "Would you come near for a bit?",  
                "Could you pop over this way?"
            }},
            {"Talk", new List<string> {
                "Any ideas?",  
                "What do you think?",  
                "Got any thoughts?",  
                "Any clue what’s going on?",  
                "Do you have any suggestions?",  
                "What’s your take on this?",  
                "Any theories?",  
                "Think we missed something?",  
                "Do you see anything I don’t?",  
                "Have any ideas?",  
                "What’s your opinion?",  
                "Any thoughts on this?",  
                "Can you figure anything out?",  
                "Think of anything useful?",  
                "Anything stand out to you?",  
                "Any hints you can spot?",  
                "What’s your plan?",  
                "Have you noticed anything?",  
                "Think we should try something?",  
                "Any guesses?",
                "Any thoughts?",  
                "What’s your idea?",  
                "Think we’re missing something?",  
                "Got any suggestions?",  
                "See anything unusual?",  
                "What do you make of this?",  
                "Any clues?",  
                "Do you notice anything?",  
                "Got a hunch?",  
                "Anything I’m overlooking?",  
                "Think of anything?",  
                "What do you reckon?",  
                "Any leads?",  
                "Have a guess?",  
                "Notice anything odd?",  
                "Got an idea?",  
                "What’s catching your eye?"
            }},
            { "Give Item", new List<string> {
                "Here, can you hold this.",  
                "Take this for a moment.",  
                "Could you hold this?",  
                "Here, Hold this.",  
                "Can you hold onto this?",  
                "Take it for now.",  
                "Here, keep this for me.",  
                "Hold this for a second.",  
                "I need you to hold this.",  
                "Here, grab this.",  
                "Would you hold this?",  
                "Take this, please.",  
                "Could you take this for me?",  
                "Here, just hold this for a bit.",  
                "I’m handing this over to you.",  
                "Mind holding this?",  
                "Here, keep it safe for now.",  
                "Can you manage this for me?",  
                "Take it, I’ll need it later.",  
                "Hold on to this for a moment.",  
                "Would you mind holding this?",  
                "Here, this is yours for now.",  
                "I’m giving this to you.",  
                "Please hold this for me.",  
                "You can take this.",  
                "Here, this might be useful to you.",  
                "Could you keep this for a moment?",  
                "Take it, just for now.",  
                "I need you to keep this safe.",  
                "Would you take care of this?",  
                "Please take this.",  
                "Keep this close.",  
                "Take this off my hands."
            }},
            { "Take Item", new List<string>
            {
                "I'll take that back now.",
                "Can I have the item back?",
                "Could you pass the item back?",
                "May I have that back?",
                "Could you hand that back?",
                "I need the item back.",
                "Mind passing that back?",
                "Let me have that item back.",
                "Could you give that back?",
                "May I get that back?",
                "I'll grab that back.",
                "Let me take that back.",
                "Pass me the item.",
                "Give me the item back.",
                "I'll take that item.",
                "Pass that here.",
                "Could you pass that here?",
                "Let me have that.",
                "Can I get that back?",
                "Hand that back here.",
                "Give that to me.",
                "Can I get that from you?",
                "I’m taking that back now.",
            }},
            { "Inquire Item", new List<string> {
                "What is that?",
                "Can you tell me what that is?",
                "Do you know what that does?",
                "What do you make of that?",
                "Any idea what it is?",
                "What’s that for?",
                "Does that mean anything to you?",
                "Do you recognize that?",
                "What would you use that for?",
                "Tell me about that.",
                "Can you examine that?",
                "Any clue what that could be?",
                "Is that useful?",
                "Could that be a key?",
                "Could that do anything here?",
                "Does it look familiar?",
                "Does that match anything we’ve seen?",
                "Would you know what to do with it?",
                "Does it look important?",
                "Could that open something?",
                "Could that be part of a puzzle?",
                "Anything odd about it?",
                "Think that belongs anywhere here?",
                "Would that fit somewhere?"
            }},
            { "Start Dialogue", new List<string> {
                "Hey..",  
                "So..",  
                "Yo..",  
            }},
            { "Cancel", new List<string> {
                "Never mind that.",  
                "Actually, nothing.",  
                "Never mind.",  
                "Scratch that.",  
            }},
        
        
            //NPC//
            { "Npc Call", new List<string> {
                "On my way!", 
                "Be right there!", 
                "Coming!", 
                "Sure thing!", 
                "Right behind ya!", 
                "In a jiffy!", 
                "Here I come!", 
                "You got it!", 
                "Zip-zip, on my way!", 
                "Okie-dokie!", 
                "Coming right up!", 
                "Yessir, on my way!", 
                "Just a sec, I’m zoomin’!", 
                "Absolutely, be right there!", 
                "Hop-skip-and-jump, here I come!",
                "Right away!",  
                "Here I go!",  
                "Absolutely!",  
                "Gotcha, on my way!",  
                "Speedy delivery!",  
                "Already on it!",  
                "Coming through!",  
                "One hop and I’m there!",  
                "Yup yup, coming!",  
                "Yes, boss!",  
                "Righto!",  
                "Vroom-vroom, here I come!",  
                "Zooming over!",  
                "On the double!",  
                "Roger that!",  
                "Lightning fast, that’s me!",  
                "To the rescue!",  
                "Here comes the lamp!",
            }},
            { "Npc Redundant Call", new List<string> {
                "On my way, no need to shout!",  
                "Already moving, see?",  
                "Yep, following, following!",  
                "Sheesh, I’m right here!",  
                "Close enough, aren’t I?",  
                "Already tagging along!",  
                "Walking my little lamp legs off!",  
                "Hey, I never stopped following!",  
                "Still right behind ya!",  
                "Yeah yeah, I’m coming!",  
                "Keep your hat on, I’m here!",  
                "Alright, alright, I get it!",  
                "Trailin’ ya like always!",  
                "Still glowing along after you!",  
                "Relax, I’m practically next to ya!",  
                "Marching my tiny feet as fast as I can!",  
                "On your tail, don’t worry!",  
                "Come on, give me some credit, I’m here!",
                "Whoa, I’m literally right here!",  
                "Geez, I’m practically your shadow!",  
                "Sheesh, no faith in your lamp buddy?",  
                "Right here, right here, chill!",  
                "I didn’t vanish, promise!",  
                "Already toddling after ya!",  
                "Don’t gotta tell me twice!",  
                "Not fast enough for ya, huh?",  
                "Still shuffling right behind!",  
                "Look over your shoulder, that’s me!",
            }},
            { "Npc Arrival", new List<string> {
                "You called?",  
                "What’s up?",  
                "Hey there!",  
                "Yes?",  
                "Here I am, what’s going on?",  
                "What do you need?",  
                "Did you need me?",  
                "I’m here, what is it?",  
                "Right here, what’s up?",  
                "You need something?",  
                "Hey! What’s happening?",  
                "What’s going on?",  
                "I’m listening!",  
                "Here, what’s up?",  
                "Found something?",  
                "Need a hand?",  
                "What did you see?",  
                "Looking for something?",  
                "Do you need help?",  
                "Something catch your eye?",  
                "Is there something I should check?",  
                "Anything interesting?",  
                "What’s the plan?",  
                "Did you figure something out?"
            }},
            { "Npc Affirmative", new List<string> {
                "Got it.",  
                "Sure thing.",  
                "Alright.",  
                "Okay.",  
                "Understood.",  
                "All set.",  
                "Copy that.",  
                "Alrighty.",  
                "On it.",  
                "Gotcha.",  
                "Perfect.",  
                "Sounds good.",  
                "Will do.",  
                "Right.",  
                "Okay, noted.",  
                "Alright, understood.",  
                "Sure.",  
                "Fine.",  
                "Absolutely."
            }},
            { "Npc Cancel", new List<string> {
                "Okay.",
                "Alright then.",
                "Sure, no problem.",
                "Alright.",
                "Oh, okay then.",
                "Oh, alright then!", 
                "Changed your mind?", 
                "No worries.", 
                "Heh, okay!", 
                "Cool, cool.", 
            }},
            { "Npc Unknown Item", new List<string> {
                "No idea what this is.",  
                "Can’t tell what it does.",  
                "I’m not sure what this is.",  
                "Don’t know what it’s for.",  
                "No clue about this one.",  
                "doesn't ring a bell.",  
                "I can’t make sense of it.",  
                "Not sure how to use this.",  
                "Beats me.",  
                "Sorry, I don’t know.",  
                "I can’t say I know what this is.",  
                "No idea what that’s used for.",  
            }},
            { "Npc Roam", new List<string> {
                "I’ll go poke around a bit!",  
                "Gonna check this side out!",  
                "I’ll have a little wander, back soon!",  
                "Time for me to snoop around again!",  
                "I’ll be over here if you need me!",  
                "I’ll keep scouting the place!",  
                "Gonna see what’s hiding in the corners!",  
                "I’ll go do some more investigating!",  
                "I’ll keep looking around while you do your thing!",  
                "I’ll float about a bit, call if you need me!",
                "Going to see what’s over here!",  
                "I’ll be over here for a bit!",  
                "Gonna poke around a little!",  
                "I’ll scout around a bit!",  
                "I’m going to have a look over there!",  
                "I’ll see what’s going on over there!",  
            }},
        };
    }
}
