using System.Collections.Generic;

public static class GenericLines
{
    public static  List<string> callLines = new List<string>
    {
        "Come here for a sec.", 
        "Hey, come here for a bit.", 
        "Could you come here for a moment?", 
        "Pop over here for a sec.",
        "Mind coming over here?",  
        "Could you come here a sec?",  
        "Would you come here for a bit?",  
        "Can you come over for a moment?",  
        "Come here when you can.",  
        "Over here for a sec?",  
        "Would you step over here?",  
        "Can I get you over here for a moment?",  
        "Could you come this way a bit?",  
        "Over here, if you don’t mind.",  
        "Can you come closer for a sec?",  
        "Would you come by for a bit?",  
        "Can you step over here a moment?",  
        "Mind stepping over here?",  
        "Would you come stand by me for a sec?",  
        "Over here, just for a moment.",  
        "Could I call you over here a sec?",  
        "Come here for a moment, please.",  
        "Would you come near for a bit?",  
        "Could you pop over this way?"
    };  

    public static List<string> npcCallLines= new List<string>
    {
        "On my way!", 
        "Be right there!", 
        "Coming!", 
        "Sure thing!", 
        "Right behind ya!", 
        "In a jiffy!", 
        "Here I come!", 
        "You got it!", 
        "Zip-zip, on my way!", 
        "Okie-dokie!", 
        "Coming right up!", 
        "Yessir, on my way!", 
        "Just a sec, I’m zoomin’!", 
        "Absolutely, be right there!", 
        "Hop-skip-and-jump, here I come!",
        "Right away!",  
        "Here I go!",  
        "Absolutely!",  
        "Gotcha, on my way!",  
        "Speedy delivery!",  
        "Already on it!",  
        "Coming through!",  
        "One hop and I’m there!",  
        "Yup yup, coming!",  
        "Yes, boss!",  
        "Okie dokie lokie!",  
        "Righto!",  
        "Vroom-vroom, here I come!",  
        "Zooming over!",  
        "On the double!",  
        "Roger that!",  
        "Lightning fast, that’s me!",  
        "To the rescue!",  
        "Here comes the lamp!",
    };

    public static List<string> redundantNpcCallLines = new List<string>
    {
        "On my way, no need to shout!",  
        "Already moving, see?",  
        "Yep, following, following!",  
        "Sheesh, I’m right here!",  
        "Close enough, aren’t I?",  
        "Already tagging along!",  
        "Walking my little lamp legs off!",  
        "Hey, I never stopped following!",  
        "Still right behind ya!",  
        "Yeah yeah, I’m coming!",  
        "Keep your hat on, I’m here!",  
        "Alright, alright, I get it!",  
        "Trailin’ ya like always!",  
        "Still glowing along after you!",  
        "Relax, I’m practically next to ya!",  
        "Marching my tiny feet as fast as I can!",  
        "On your tail, don’t worry!",  
        "Come on, give me some credit, I’m here!",
        "Whoa, I’m literally right here!",  
        "Geez, I’m practically your shadow!",  
        "Sheesh, no faith in your lamp buddy?",  
        "Right here, right here, chill!",  
        "I didn’t vanish, promise!",  
        "Already toddling after ya!",  
        "Don’t gotta tell me twice!",  
        "Not fast enough for ya, huh?",  
        "Still shuffling right behind!",  
        "Look over your shoulder, that’s me!",  
    };
    public static List<string> npcArrivalLines = new List<string>
    {
        "You called?",  
        "What’s up?",  
        "Hey there!",  
        "Yes?",  
        "Here I am, what’s going on?",  
        "What do you need?",  
        "Did you need me?",  
        "I’m here, what is it?",  
        "Right here, what’s up?",  
        "You need something?",  
        "Hey! What’s happening?",  
        "What’s going on?",  
        "I’m listening!",  
        "Here, what’s up?",  
        "Found something?",  
        "Need a hand?",  
        "What did you see?",  
        "Looking for something?",  
        "Do you need help?",  
        "Something catch your eye?",  
        "Is there something I should check?",  
        "Anything interesting?",  
        "What’s the plan?",  
        "Did you figure something out?"
    };
    public static List<string> npcRoamLines = new List<string>
    {
        "I’ll go poke around a bit!",  
        "Gonna check this side out!",  
        "I’ll have a little wander, back soon!",  
        "Time for me to snoop around again!",  
        "I’ll be over here if you need me!",  
        "I’ll keep scouting the place!",  
        "Gonna see what’s hiding in the corners!",  
        "I’ll go do some more investigating!",  
        "I’ll keep looking around while you do your thing!",  
        "I’ll float about a bit, call if you need me!",
        "Going to see what’s over here!",  
        "I’ll be over here for a bit!",  
        "Gonna poke around a little!",  
        "I’ll scout around a bit!",  
        "I’m going to have a look over there!",  
        "I’ll see what’s going on over there!",  
    };

}
